[package]
name = "turbocache"
version = "0.0.1"
authors = ["Aditya Motale <adityamotale.22@gmail.com>"]
edition = "2021"
description = "Persistent, high-performance, disk-backed Key-Value store"
license = "MIT"
repository = "https://github.com/frozen-lab/turbocache"
keywords = ["key-value", "database", "persistent"]
categories = ["database", "caching"]

[lib]
path = "src/lib.rs"

[dependencies]
memmap2 = "0.9.5"
thiserror = "2.0.12"

[dev-dependencies]
criterion = "0.5.1"
tempfile = "3.19.1"

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false
