[package]
name = "turbofox"
version = "0.0.1"
edition = "2024"
description = "A persistant and embedded KV Database built for on-device caching."
license = "Apache-2.0"
repository = "https://github.com/frozen-lab/turbofox"
keywords = ["key-value", "database", "persistent", "store", "simd"]
