[package]
name = "turbocache"
version = "0.0.2"
edition = "2021"
description = "Persistent, high-performance, disk-backed Key-Value store"
license = "MIT"
repository = "https://github.com/frozen-lab/turbocache"
keywords = ["key-value", "database", "persistent"]
categories = ["database", "caching"]

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.98"
memmap = "0.7.0"
siphasher = "1.0.1"

[dev-dependencies]
criterion = "0.6.0"
tempfile = "3.20.0"

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false
