[package]
name = "turbocache"
version = "0.0.3"
edition = "2021"
description = "Persistent, high-performance, disk-backed Key-Value store"
license = "MIT"
repository = "https://github.com/frozen-lab/turbocache"
keywords = ["key-value", "database", "persistent", "store", "db"]

