[package]
name = "turbocache"
version = "0.1.0"
edition = "2024"
description = "A persistant and embedded KV Database built for on-device caching."
license = "Apache-2.0"
repository = "https://github.com/frozen-lab/turbocache"
keywords = ["key-value", "database", "persistent", "store", "simd"]
exclude = ["flake.nix", "flake.lock", "logger/", "hasher/"]

[dependencies]
memmap2 = "0.9.7"
hasher = {path = "./hasher", version = "0.1.0"}
logger = {path = "./logger", version = "0.1.0"}

[dev-dependencies]
sphur = "0.2.0"
tempfile = "3.20.0"

[[bench]]
name = "bench"
path = "benchmarks/bench.rs"
harness = false

[workspace]
members = ["hasher", "logger"]
