[package]
name = "turbocache"
version = "0.0.1"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
memmap2 = "0.9.5"
thiserror = "2.0.12"

[dev-dependencies]
criterion = "0.5.1"
tempfile = "3.19.1"

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false
