[package]
name = "turbocache"
version = "0.0.3"
edition = "2021"
description = "Persistent, high-performance, disk-backed Key-Value store"
license = "MIT"
repository = "https://github.com/frozen-lab/turbocache"
keywords = ["key-value", "database", "persistent", "store", "db"]

[dependencies]
memmap2 = "0.9.7"
twox-hash = {version = "2.1.1", features = ["xxhash3_64"]}

