[package]
name = "turbocache"
version = "0.0.5"
edition = "2021"
description = "A persistant and embedded KV Database built for on-device caching."
license = "MIT"
repository = "https://github.com/frozen-lab/turbocache"
keywords = ["key-value", "database", "persistent", "store", "frozen-lab"]

[dependencies]
memmap2 = "0.9.7"
