name: Build, Release & Publish

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  id-token: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Test and build
        run: cargo test --locked && cargo build --locked
      - name: Auth
        uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - name: Publish to `crates.io`
        run: cargo publish --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

