name: Release

on:
  push:
    tags:
      - 'v*.*.*'

  # allow manual trigger
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache-key: ${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Benchmarks
        run: python3 bench.py

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
          body_path: BENCH_RESULTS.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
  
      - name: Auth
        uses: rust-lang/crates-io-auth-action@v1
        id: auth
        
      - name: Publish to `crates.io`
        run: cargo publish --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
