name: Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-linux-x86:
    name: Linux x86_64
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: cargo build --verbose
        
      - name: Run tests
        run: cargo test --workspace --verbose

  test-windows:
    name: Windows
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: cargo build --verbose
        
      - name: Run tests
        run: cargo test --workspace --verbose

  test-linux-arm64:
    name: Linux ARM64
    runs-on: ubuntu-20.04-arm64
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: cargo build --verbose
        
      - name: Run tests
        run: cargo test --workspace --verbose

