name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # allow manual trigger
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
          - os: windows-latest
            arch: x86_64
          - os: windows-11-arm
            arch: aarch64
          - os: macos-13
            arch: x86_64
          - os: macos-latest
            arch: aarch64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache-key: ${{ hashFiles('**/Cargo.lock') }}

      - name: Test aarch64 (NEON)
        if: matrix.arch == 'aarch64'
        run: cargo test --release -- --nocapture

      - name: Test x86_64 (SSE2)
        if: matrix.arch == 'x86_64' && runner.os != 'Windows'
        run: RUSTFLAGS="-C target-feature=+sse2" cargo test --release -- --nocapture

      - name: Test x86_64 (AVX2)
        if: matrix.arch == 'x86_64' && runner.os != 'Windows'
        run: RUSTFLAGS="-C target-feature=+avx2" cargo test --release -- --nocapture

      - name: Test x86_64 (SSE2) [WIN]
        if: matrix.arch == 'x86_64' && contains(matrix.os, 'windows')
        shell: pwsh
        env:
          RUSTFLAGS: "-C target-feature=+sse2"
        run: cargo test --release -- --nocapture

      - name: Test x86_64 (AVX2) [WIN]
        if: matrix.arch == 'x86_64' && contains(matrix.os, 'windows')
        shell: pwsh
        env:
          RUSTFLAGS: "-C target-feature=+avx2"
        run: cargo test --release -- --nocapture

  examples:
    needs: unit_tests
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
          - os: windows-latest
            arch: x86_64
          - os: macos-13
            arch: x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache-key: ${{ hashFiles('**/Cargo.lock') }}

      - name: Default Example (Linux/Mac)
        if: runner.os != 'Windows'
        run: RUST_LOG=trace cargo run --example basic --release

      - name: Turbo Buckets Example (Linux/Mac)
        if: runner.os != 'Windows'
        run: RUST_LOG=trace cargo run --example turbo_buckets --release

      - name: Default Example (Windows)
        if: runner.os == 'Windows'
        run: cargo run --example basic --release

      - name: Turbo Buckets Example (Windows)
        if: runner.os == 'Windows'
        run: cargo run --example turbo_buckets --release

  benchmarks:
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache-key: ${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Benchmarks
        run: |
          taskset -c 1 python3 run_bench.py --sample 24

      - name: Print Summery
        run: |
          echo "Adding bench results to job summary..."
          cat BENCH_RESULTS.md >> $GITHUB_STEP_SUMMARY
