name: WIN (x86)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: cargo build --verbose
        
      - name: Run Simple Example
        run: cargo run --example simple
        
      - name: Run Multithreading Example
        run: cargo run --example multithreading
        
      - name: Run tests
        run: cargo test --release -- --nocapture
